### ISSUE TITLE
Matrix multiplication with MatrixXd

### ISSUE THREAD

**Issue by b1gb4dw0lf** [vancegroup/EigenArduino#2]
Hello,

I am currently using this library with Arduino Mega 2560, but I am having an issue with matrix multiplication that is it is not returning any solution. For example consider example below:

```
#include <stlport.h>
#include <Eigen30.h>
#include <Eigen/LU>
#include <Eigen/Dense>

Eigen::MatrixXd b, c;

void setup() {
  Serial.begin(9600);
  Eigen::MatrixXd a;

  for(int i=0; i < 4; i++){
    for(int j=0; j < 4;j++){
      a(i,j) = 1;
    }
  }

  c = a * a;

}

void loop() {

}
```

This code returns a matrix like below:

```
1 1 1 1 
1 1 1 1
1 1 1 1 
1 1 1 1 
```

Or if I define the matrix as

```
Eigen::MatrixXd a(4,4);
```

And then initialise it to all one, the multiplication operation does not return anything. Am I using the library wrong or is there a problem with this library?

**Comment by rpavlik** [comment]
I think you may be using it wrong, but this is more of question for the
upstream eigen documentation. Ideally, if you know the size of your matrix
ahead of time, don't use the X typedefs, use the fixed size types: they'll
avoid additional memory allocation, probably run faster, and be easier to
use (I'm guessing this code would be fine if you had a matrix44d instead)

This repo just contains the small adaptations to an old version of eigen
needed to run on the arduino. (It could probably be updated to a newer
version at some point but that wouldn't solve your problem)
