### ISSUE TITLE
Can't compilate "fatal error: cstddef: No such file or directory"

### ISSUE THREAD

**Issue by ripponds** [vancegroup/EigenArduino#4]
Hi, 

Literally can't compilate ALWAYS console shows this error 

```
fatal error: cstddef: No such file or directory
#include <cstddef>
```

And the program program is literally 
```
#include <Eigen30.h>
#include <EigenAVR.h>

void setup() {
  // put your setup code here, to run once:

}

void loop() {
  // put your main code here, to run repeatedly:

}
```
In any program I get that error

I don't know what to do :(

Kind regards.

![GitHub3](https://user-images.githubusercontent.com/71950128/97148234-ca071000-1738-11eb-8dea-d5a5e9f1fc8a.png)

**Comment by rpavlik** [comment]
Per the readme, you need a C++ standard library implementation. Your choices are better today than they were back when I last used this, it's not too painful to modify libc++ to work in arduino.
